name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        node: ["12", "14"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Test (node ${{ matrix.node }}, ${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install -f
      - name: Test
        if: matrix.os != 'ubuntu-latest'
        run: npm test
      - name: Test with xfvb
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run npm test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install -f
      - name: Lint
        run: npm run lint
